-- Total rows of data --
SELECT COUNT(*) TOTAL_ROWS
FROM SUPERSTORE
;
-- Top 10 cites have highest sales --
SELECT CITY
    , SALES
    ,SUM(SALES)
FROM SUPERSTORE
GROUP BY CITY
    , SALES
ORDER BY SUM(SALES) DESC
FETCH FIRST 10 ROWS ONLY
;
--Profit by region --
SELECT REGION
    , SUM(PROFIT)
FROM SUPERSTORE
GROUP BY REGION
ORDER BY SUM(PROFIT) DESC
;